language: node_js

node_js:
  - "node"   # Latest stable Node.js release
  - "lts/*"  # Latest LTS Node.js release

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn coverage; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn test; fi
  - yarn lint

deploy:
  - provider: npm
    email: mattias.kindborg@gmail.com
    api_key:
      secure: JzIVxA5gsmcEZwtd4k9o1LUaMg8R3+SH9AO14+2yy/tC8LY6aVSCVUHizgQMvSFXUQlOUyzQPUEBEVbGwvdLpn+I5TRR/efPd91VxO+tiVKq+InhKlKAfMkmbPeaVLc1V3YBInoZUZynU/9xksEhOo3LYPNLSFK4odCgTY8HkM9RAFc2twCaVPh2O+3zg2C5mUhi2CKL6j6SOVs0+OEOsdsveuGxm18DBgDs7AbAoynlZarXKwbQukYMCUylxtuBaN5ggsGvhI1iimYVSm363zZWrOY8lqa+RhTWg8vQS7VpgriDUyNDyvr91vD6j+OEIRUZYiXisNUkghXWbsO9iuXLzQsUFKjZx6eCQCRATiYwxnYP/KGsGM8byHud4h6yJq9SGgpz6NWKKWB2/gUuEnkakrIAs5lEWZXyDjTEOFrOj5v/fr7lNdctfhcb3HDVD9Kn4qDzm7C08dlUssEI7LRQIt92t5nr20BpsOE5MWxldzgkpGVRleQjhsJcqrkYfjwxfrPeiwTo6ZDU3eJDdV/RQav89g4Y/TgD4VmCfsbBDairEImcp3Dplzsq/YN/QLQWuG31t9DS8M4w65Wd4YLQb7fEda0FSACeTRRCM8c2PKsYnbH6q/ZWOpiJpMsHn5FrIVQnBMmcoHAkKuczkSFPOZ+AoUzxdLcnXNXaGgc=
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: a+6n90LE9Elyw8zG8AWmp+HKMvNWYcLa8E61TA/KLNfZ2pNPFeAWf4O2zWPohHH+Qbt6EHZdm1zkxFhE+wOZvepc+b1m4z3enHsVN85D29jpH1drEI9zvzt47tnYSBhZe21W/zVX7K2KwrYa6DsqomcEA8dfT9K7wWdSraVAf+Jb4+WIbHpqPykIpb7eJ6AzTWdiSo/KIjwpNqphChX3iXx5oJlDFmiXM7Ef+yus+ACaE4Vr/Ml/xRUXeYn7jMweHnm0Ul8DeOs4Yljn1O+AUFObCxoft8ad0q6NKW5ZVa6+LH7nWd8UkZ3an0wxIQi0FtsbDg1aFyNrxtasdF1TY0Y2lsj3r83oh2rWFY3FWugvvlBGK/GXuRixjj7mtZb92u71DuBJMJZZ80XXoDeTLBcGmoDZVqBYiZRvZTQMVImsWbOoXQeXLIFGVRpOfZL41Fsakg17SIM9Q7SROO7gjnyrgvOb5mfTPrM6qU3MYwn+v9i0CGMc8XVTz3RfnrYY1KtR40OOPNwvSLsX8ffP4RPSj4hmOV219GpnvyA9F3dVIZ3g1io5OJR3uuMR/YXebzVXVsziiu6P965FhlVretsUvBjUjEr76slyn8cTwChd9li6OXfwz0In3o8XYzcNpS3CA8QTvyyra3EXebOwZOTnhHXE754Sai8uIODe0uE=
    on:
      tags: true
