language: node_js

node_js:
  - "node"   # Latest stable Node.js release
  - "lts/*"  # Latest LTS Node.js release

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn coverage; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn test; fi
  - yarn lint

deploy:
  - provider: npm
    email: mattias.kindborg@gmail.com
    api_key:
      secure: gdf3AcE2V2FRMZKzofdkytZGXWi4UQkv6hZzaLlC4PguXBu3Cey0gmUJ5z7rCmu/SloCB+5LLeKO1SBo3YYfA8c/6ytvkXfqQRxVJtKNa7XnSi5dgEOZgPVPWU2+FLfBpWPxOkpYWjPVcRl/UtjdZ0j3v4I+8k/UuBQggX/jyRsSegnYNJLo3kcqb0ZTZGtU7j+tpybFR79EpBcu4RNmegpROd+ECuCr5bp/X7oStE1y8ERoSV08UuhfYCl94rO+BxODGfS/0Z06yxZb7Uta2f909O/t4OgzxVLpdTSbU9DtYzXAdjXTUqUIfslQVv0nOHekTh+g5a6q5LVOQk4ZWh63PEh+uFGR6R1QFnZ4AzG20Ppf4LzIqeS78RAG1hbjzCKH8fTx921LksOdSPa6rXV6TwXPRxM87nqNSg+c9r0FaDGXDq9Drt21hO50EIYRiPuzwk+sL668Zd/iolJ3wWmyrZCPTfWdbakFIWtZyyJTkBEIJEas5xB60DsRqdx8EbQpfRh2qgL1574UBaJciBWUyHCvk+dzJ2LBOBRESvjtOslBaw+76asAawSDLSzlu2kGl2N1fSlAMxopUDIuOf4D9G0hpgklPEHtO7qye7QpG4S430OqbCZg8wEJY4AD+7Qp5aiGXHfhpgHcFi8DPWujHo2Dkj6ZUmuXf28jnLs=
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: JAUJTYksBe1/KKLjYIpjvBIzpFOo/6NAupoodBfSljbScSzJlKZ2tf5t1oyMY988b39iYt3IDeeVSm7dEbXfMMpHYKPSjkjI5+g95kberAsBZHQrgCBGtYbHm04anJiYCgOCHwK4eVHMYHP3zsbliOT2o76M1gfXYemxJaNLDYWUK5C45jelVo+O1yowqgfE+XovgMWR3bRo7JSX6jQpErjcm8UVXOTrpiY2hhI+7GO5whtMDZBtg23GtoYAtJ0SWchSbvNoHONSVJR/zXERzpoowGtnjN/ptYwyv4AL6YylpbmHyKPhdTBE4wuSe8LJkKmZ3Y2ubWfeumiXqofr19+Dr9TLj1OPzIUpqYHhHpodZI2uBx+UDnFdJk+rewoEbSk6YVP6FlOvGH8TRDqAybrem55RRGAmCWjqAXdGFhuOgekIjSsoNTjTtu3fmK+Jsw0ozD3pPDY1PPV45W1NHLvegqCrmXUhO3EWwmcTchgXpWe4adDnlQlZRQIc4LJS26MwAnciPbVJR5geT0APafLKfip1ghY+ZAvaOCPp8bTgebqGVubG+hYyIzOzLsxyQePg7nKM2LtKW4fR68eXwz4GmjcdxWlurlqBsTa1QgP3V+QrVe9mETVumgcsm7GGJjzN6dKqddSe1sjAgLQiVOLvKdWEZzQ4YC3K96XFwUY=
    on:
      tags: true
