language: node_js

node_js:
  - "node"   # Latest stable Node.js release
  - "lts/*"  # Latest LTS Node.js release

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn coverage; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn test; fi
  - yarn lint

deploy:
  - provider: npm
    email: mattias.kindborg@gmail.com
    api_key:
      secure: Cz+EzoS0fVIt54AkGHg3tl9nQ8mQ2yEu2FzsVAJapxR6HbNytdN1myca/sPdXUh8zFctAeBMz3XZIhYuDc2eRFD0SR5d9IgzepLcZwUoGwRG+C1uffRqAie4/OAGfI15hTInPKHJ/jHqdYyd1/YzBe3eeR4w0OMmqQoTNo7Q9e3SHBIHzU0xUnZODMG9VmTARQYQ5qLNKpgqJmSmNeZ83e/i7dgLi1xSq3DTN+mqMwHRdzuTqoVk/PdBVbCpUAdxSU1jl/s9fdJfK2xC28PlrlRV+ovmz9BT8PNULQtb1rKKBeRkT/AIH2fH3pnlg+S0/DxRV7WVBJfwPTDJaLqzFKVLqUcVj9gdY+5NqN0pb3ZhxFw5YVbYnK1uWtpcBvgIcs0+G3PW8qwlPzLWnDHeHzc7WY8ePW5dJlGoS9fHIlCOJ2g1B3R04LCrrAqIxaFpIMkL6kDvoxQ+W7bJRxJFDP7wQnLp7nrzIRYdGTWdzFYQXt60v8yPA+9Z7B3Ovbop3QYco6w9uU1vuaiSVIElGzNF8c00sXZ2VQd2BkPDMRt/CamNiUtgAda0ybgtSlkW/20d6ElgSdsv8+xxQCv85faMlvHffzX9NXUhxz/X/nMMio0a0wmnODmGJs4ggvsIg/Oe6SC3QCX6C1F42xVIU9PC5rYpqc4Ztk18yPNZdgM=
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: WEw6WTmyLD7xx7Jx6GyTprVQmwllHIsmon6B2LrsisG/ud/vxc/DxnTDfCEfLKzmlLUyT4HMs5VdxEz/QwRCNLMMUc2+426R9tE7Kgxxct7Jqy2d9FiLydRktuN6ipyU+/XyXpiRUHAUFovhWo1l5mDqjpBpRmID+TPcLmsAPvUyhyzCPUd6pEEtc7DW5ZbAID5Y00/w+eeH0Xz7UJUHdtgxmW+2aH2sq++VqEgtpTsq/o9pM9BV0rgZkqYfQzC0wSlvjeSKV8Vyn1MgcgI/hiqnD1sWSiO20GozfQO2J58g3CAm408W5Lh8ZOaldv2DhPCfKSBJC9J7vHZ5mzb6gLZPgczMmaKvu00CZwXY+7pbdrMmkA5wznThBbrig5+k2pyZEAPuBvHUd+8jfcxMjnBpNAWDcnMOGEx9IhAcynstrhvrbFmKecaF6OaXagjfSywUGRrE+zZoi3pXSUV3qQZUhuaxTcl2JbKDz8Vqe6YsrHHyOT/WNPv5LNj+wqPYv1c9r+BB//He2Qppv5XhCHXNYwnimlV3h81K/wWndGF7tR9fo3DiBYUH0paZGkSkssJDYEQwqxViZynbReYXqeC+6oQ028az9XWNkI/yEyJOLVLMadXsVzfWiWeRKKwIlKUHCgnmeZ7S/1vJprYvQuwe0NDg3bIrvWWqVrYDoRE=
    on:
      tags: true
